# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'Louzet'
name: 'Symfony Action'
description: 'Run symfony via GithubAction.'

inputs:
    dir:
        description: "The project directory"
        required: true
        default: ""
    env_file:
        description: "Path to an localized env file"
        required: true
        default: ".env.dist"

runs:
    using: 'node12'
    main: 'index.ts'


branding:
    icon: 'check'
    color: 'blue'
