name: Code Quality

on:
  pull_request:
    branches:
      - master
      - develop

  push:
    branches:
      - master
      - develop

jobs:
  code_quality:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos-latest')
        run: npm run prettier:format:check

      - name: Run eslint
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos-latest')
        run: npm run lint

      - name: Run build
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos-latest')
        run: npm run build
