name: Main

on:
  pull_request:
    branches:
      - master
      - dev

  push:
    branches:
      - master
      - dev

jobs:
  node:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: symfony action
        uses: Louzet/symfony-action@master
        with:
          dir: "./test"
          env_file: '.env'
