name: Node workflow

on:
  pull_request:
    branches:
      - master
      - dev

  push:
    branches:
      - master
      - dev

jobs:
  run:
    name: setup node before symfony-action
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        if: startsWith(matrix.os, 'ubuntu-latest') || startsWith(matrix.os, 'macos-latest')
        run: npm run prettier:format:check

      - name: Run eslint
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: symfony action
        uses: Louzet/symfony-action@master
        with:
          dir: "./test"
          env_file: '.env'
